version: '3.1'

services:
  db:
    image: postgres:11
    container_name: ps_files_hash
    # restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ~/Documents/databases/files_hash/postgres:/var/lib/postgresql/data
